Numpy 

 - create array 
 - maths 
 - operations 

without numpy doing maths (matrix maths )is very complex in any language 

In [1]:
x = [[1,2,3],
     [3,2,1]]
print(x)     



[[1, 2, 3], [3, 2, 1]]


In [1]:
x = [5,8,9,6,2,9]
print(x)
for i in x :
    

[5, 8, 9, 6, 2, 9]


In [3]:
import numpy as np 

In [4]:
x = np.array([
    [1,2,3],
    [3,4,5]
])
print(x)
print(type(x))
print(x.shape)

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
(2, 3)


In [5]:
print(x.sum())
print(x.sum(axis= 0))
print(x.sum(axis = 1))


18
[4 6 8]
[ 6 12]


In [7]:
a = np.array([1,2,3])
b = np.array([[1,1],[2,2],[3,3]])
c= np.array([[[1,1],[2,2],[3,3]]])

print(a.shape , a.ndim)
print(b.shape , b.ndim)
print(c.shape , c.ndim)


(3,) 1
(3, 2) 2
(1, 3, 2) 3


#matrix creation 

- sequential 
    - arrange 
    - linspace 
- random 
    - rand 
    - randint 
    - uniform     


In [4]:
x = np.arange (1,11,0.5)  #arange tells .5  tells diffrence  
print(x)


#linspace tells number of points 
y =np.linspace(1,11,14)
print(y)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]
[ 1.          1.76923077  2.53846154  3.30769231  4.07692308  4.84615385
  5.61538462  6.38461538  7.15384615  7.92307692  8.69230769  9.46153846
 10.23076923 11.        ]


In [12]:
np.arange(1,11,0.5).reshape(5,4)

array([[ 1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5]])

In [15]:
y = np.arange(1,11)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
np.arange(1,11,.5).reshape(5,2,2)

array([[[ 1. ,  1.5],
        [ 2. ,  2.5]],

       [[ 3. ,  3.5],
        [ 4. ,  4.5]],

       [[ 5. ,  5.5],
        [ 6. ,  6.5]],

       [[ 7. ,  7.5],
        [ 8. ,  8.5]],

       [[ 9. ,  9.5],
        [10. , 10.5]]])

In [17]:
x1 = np.array([[1,2,3],[4,5,6]])
x2 = np.array([[4,2,3],[2,6,6]])

In [20]:
print(x1)
print(x2)
print(x1+x2)
print(x1 - x2)
print(x1*x2)
print(x1/x2)
print(x1//x2)
print(x1%x2)
print(x1**x2)

#comparison in numpy results in boolean array
print(x1<x2)
print(x1>x2)
print(x1<=x2)
print(x1>=x2)


[[1 2 3]
 [4 5 6]]
[[4 2 3]
 [2 6 6]]
[[ 5  4  6]
 [ 6 11 12]]
[[-3  0  0]
 [ 2 -1  0]]
[[ 4  4  9]
 [ 8 30 36]]
[[0.25       1.         1.        ]
 [2.         0.83333333 1.        ]]
[[0 1 1]
 [2 0 1]]
[[1 0 0]
 [0 5 0]]
[[    1     4    27]
 [   16 15625 46656]]
[[ True False False]
 [False  True False]]
[[False False False]
 [ True False False]]
[[ True  True  True]
 [False  True  True]]
[[False  True  True]
 [ True False  True]]


In [21]:
a = np.random.rand(3,2)
a

array([[0.88527075, 0.60660946],
       [0.45734191, 0.65429971],
       [0.20426385, 0.88602389]])

In [22]:
np.set_printoptions(precision=2)

In [23]:
b = np.random.randint(0 , 10 ,(3,3))
b

array([[9, 0, 9],
       [4, 0, 7],
       [7, 7, 5]])

In [25]:
c = np.random.uniform(0 , 10 ,(5,5))
c

array([[2.21, 0.9 , 8.95, 8.72, 3.36],
       [8.24, 8.32, 6.19, 9.47, 6.25],
       [7.44, 0.08, 0.98, 3.23, 6.14],
       [2.11, 1.75, 0.14, 4.79, 5.82],
       [4.54, 1.79, 8.69, 3.97, 1.73]])